language: objective-c
osx_image: xcode8.3

env:
    global:
        - PROJECT=GLTableCollectionView.xcodeproj
        - SCHEME=GLTableCollectionView
        - SDK=iphonesimulator10.3
        - DESTINATION="platform=iOS Simulator,OS=latest,name=iPhone 5"

before_install:
    # - brew update
    # - brew upgrade
    - gem update
    - gem install xcpretty
    - gem install xcpretty-travis-formatter
    - gem clean
    - xcodebuild -version
    - xcodebuild -showsdks

script: xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug test | xcpretty -f `xcpretty-travis-formatter` && exit ${PIPESTATUS[0]}
